/**
 * Static manifest of images per folder (browser cannot list directories).
 * Naming convention: photos use <folder-slug>-NNN.jpg and logos use logo-<name>.jpg.
 */
/** ISO date (YYYY-MM-DD); deploy.ps1 sets this only when any album's photo count in this file changes. Empty hides the home footer. */
window.PORTFOLIO_LAST_UPDATED = "2026-06-20";
/** Group ids whose photo count changed on the date above; deploy.ps1 maintains this list. */
window.PORTFOLIO_LAST_UPDATED_ALBUMS = ["Furry Friends", "World"];

window.PORTFOLIO_GROUPS = [
  {
    id: "Animals",
    title: "Animals",
    folder: "Animals",
    logo: "Logos/logo-animals.jpg",
    photos: [
      "animals-001.jpg",
      "animals-002.jpg",
      "animals-003.jpg",
      "animals-004.jpg",
      "animals-005.jpg",
      "animals-006.jpg",
      "animals-007.jpg",
      "animals-008.jpg",
      "animals-009.jpg",
      "animals-010.jpg",
      "animals-011.jpg",
      "animals-012.jpg",
      "animals-013.jpg",
      "animals-014.jpg",
      "animals-015.jpg",
      "animals-016.jpg",
      "animals-017.jpg",
      "animals-018.jpg",
      "animals-019.jpg",
      "animals-020.jpg",
      "animals-021.jpg",
      "animals-022.jpg",
      "animals-023.jpg",
      "animals-024.jpg",
      "animals-025.jpg",
      "animals-026.jpg",
      "animals-027.jpg",
      "animals-028.jpg",
      "animals-029.jpg",
      "animals-030.jpg",
      "animals-031.jpg",
      "animals-032.jpg",
      "animals-033.jpg",
      "animals-034.jpg",
      "animals-035.jpg",
    ],
  },
  {
    id: "People",
    title: "People",
    folder: "People",
    logo: "Logos/logo-people.jpg",
    photos: [
      "people-001.jpg",
      "people-002.jpg",
      "people-003.jpg",
      "people-004.jpg",
      "people-005.jpg",
      "people-006.jpg",
      "people-007.jpg",
      "people-008.jpg",
      "people-009.jpg",
      "people-010.jpg",
      "people-011.jpg",
      "people-012.jpg",
      "people-013.jpg",
      "people-014.jpg",
      "people-015.jpg",
      "people-016.jpg",
      "people-017.jpg",
    ],
  },
  {
    id: "Studio",
    title: "Studio",
    folder: "Studio",
    logo: "Logos/logo-studio.jpg",
    photos: [
      "studio-001.jpg",
      "studio-002.jpg",
      "studio-003.jpg",
      "studio-004.jpg",
      "studio-005.jpg",
      "studio-006.jpg",
      "studio-007.jpg",
      "studio-008.jpg",
      "studio-009.jpg",
      "studio-010.jpg",
      "studio-011.jpg",
      "studio-012.jpg",
      "studio-013.jpg",
      "studio-014.jpg",
      "studio-015.jpg",
      "studio-016.jpg",
      "studio-017.jpg",
      "studio-018.jpg",
      "studio-019.jpg",
      "studio-020.jpg",
      "studio-021.jpg",
      "studio-022.jpg",
      "studio-023.jpg",
      "studio-024.jpg",
      "studio-025.jpg",
      "studio-026.jpg",
      "studio-027.jpg",
      "studio-028.jpg",
      "studio-029.jpg",
      "studio-030.jpg",
      "studio-031.jpg",
      "studio-032.jpg",
      "studio-033.jpg",
      "studio-034.jpg",
      "studio-035.jpg",
      "studio-036.jpg",
      "studio-037.jpg",
      "studio-038.jpg",
      "studio-039.jpg",
    ],
  },
  {
    id: "World",
    title: "World",
    folder: "World",
    logo: "Logos/logo-world.jpg",
    photos: [
      "world-001.jpg",
      "world-002.jpg",
      "world-003.jpg",
      "world-004.jpg",
      "world-005.jpg",
      "world-006.jpg",
      "world-007.jpg",
      "world-008.jpg",
      "world-009.jpg",
      "world-010.jpg",
      "world-011.jpg",
      "world-012.jpg",
      "world-013.jpg",
      "world-014.jpg",
      "world-015.jpg",
      "world-016.jpg",
      "world-017.jpg",
      "world-018.jpg",
      "world-019.jpg",
      "world-020.jpg",
      "world-021.jpg",
      "world-022.jpg",
      "world-023.jpg",
      "world-024.jpg",
      "world-025.jpg",
      "world-026.jpg",
      "world-027.jpg",
      "world-028.jpg",
      "world-029.jpg",
      "world-030.jpg",
      "world-031.jpg",
      "world-032.jpg",
      "world-033.jpg",
      "world-034.jpg",
      "world-035.jpg",
      "world-036.jpg",
      "world-037.jpg",
      "world-038.jpg",
      "world-039.jpg",
      "world-040.jpg",
      "world-041.jpg",
      "world-042.jpg",
      "world-043.jpg",
      "world-044.jpg",
      "world-045.jpg",
      "world-046.jpg",
      "world-047.jpg",
    ],
  },
  {
    id: "Japan",
    title: "Japan",
    folder: "Japan",
    logo: "Logos/logo-japan.jpg",
    photos: [
      "japan-001.jpg",
      "japan-002.jpg",
      "japan-003.jpg",
      "japan-004.jpg",
      "japan-005.jpg",
      "japan-006.jpg",
      "japan-007.jpg",
      "japan-008.jpg",
      "japan-009.jpg",
      "japan-010.jpg",
      "japan-011.jpg",
      "japan-012.jpg",
      "japan-013.jpg",
      "japan-014.jpg",
      "japan-015.jpg",
      "japan-016.jpg",
      "japan-017.jpg",
      "japan-018.jpg",
      "japan-019.jpg",
      "japan-020.jpg",
      "japan-021.jpg",
      "japan-022.jpg",
      "japan-023.jpg",
      "japan-024.jpg",
      "japan-025.jpg",
      "japan-026.jpg",
      "japan-027.jpg",
      "japan-028.jpg",
      "japan-029.jpg",
      "japan-030.jpg",
      "japan-031.jpg",
      "japan-032.jpg",
      "japan-033.jpg",
      "japan-034.jpg",
      "japan-035.jpg",
      "japan-036.jpg",
      "japan-037.jpg",
      "japan-038.jpg",
      "japan-039.jpg",
      "japan-040.jpg",
      "japan-041.jpg",
      "japan-042.jpg",
      "japan-043.jpg",
      "japan-044.jpg",
      "japan-045.jpg",
      "japan-046.jpg",
      "japan-047.jpg",
      "japan-048.jpg",
      "japan-049.jpg",
      "japan-050.jpg",
      "japan-051.jpg",
      "japan-052.jpg",
      "japan-053.jpg",
      "japan-054.jpg",
      "japan-055.jpg",
      "japan-056.jpg",
      "japan-057.jpg",
      "japan-058.jpg",
      "japan-059.jpg",
      "japan-060.jpg",
      "japan-061.jpg",
      "japan-062.jpg",
      "japan-063.jpg",
      "japan-064.jpg",
      "japan-065.jpg",
      "japan-066.jpg",
      "japan-067.jpg",
      "japan-068.jpg",
      "japan-069.jpg",
      "japan-070.jpg",
      "japan-071.jpg",
      "japan-072.jpg",
    ],
  },
  {
    id: "Furry Friends",
    title: "Furry Friends",
    folder: "Furry Friends",
    logo: "Logos/logo-furry-friends.jpg",
    sections: [
      {
        title: "Diuna",
        folder: "Diuna",
        photos: [
          "diuna-001.jpg",
          "diuna-002.jpg",
          "diuna-003.jpg",
          "diuna-004.jpg",
          "diuna-005.jpg",
          "diuna-006.jpg",
          "diuna-007.jpg",
          "diuna-008.jpg",
          "diuna-009.jpg",
          "diuna-010.jpg",
          "diuna-011.jpg",
          "diuna-012.jpg",
        ],
      },
      {
        title: "Nefri",
        folder: "Nefri",
        photos: [
          "nefri-001.jpg",
          "nefri-002.jpg",
          "nefri-003.jpg",
          "nefri-004.jpg",
          "nefri-005.jpg",
          "nefri-006.jpg",
          "nefri-007.jpg",
          "nefri-008.jpg",
          "nefri-009.jpg",
          "nefri-010.jpg",
          "nefri-011.jpg",
          "nefri-012.jpg",
          "nefri-013.jpg",
          "nefri-014.jpg",
          "nefri-015.jpg",
          "nefri-016.jpg",
        ],
      },
      {
        title: "Rest of the Pack",
        folder: "Rest of the Pack",
        photos: [
          "rest-of-the-pack-001.jpg",
          "rest-of-the-pack-002.jpg",
          "rest-of-the-pack-003.jpg",
          "rest-of-the-pack-004.jpg",
          "rest-of-the-pack-005.jpg",
          "rest-of-the-pack-006.jpg",
          "rest-of-the-pack-007.jpg",
          "rest-of-the-pack-008.jpg",
          "rest-of-the-pack-009.jpg",
          "rest-of-the-pack-010.jpg",
          "rest-of-the-pack-011.jpg",
          "rest-of-the-pack-012.jpg",
          "rest-of-the-pack-013.jpg",
          "rest-of-the-pack-014.jpg",
          "rest-of-the-pack-015.jpg",
          "rest-of-the-pack-016.jpg",
        ],
      },
    ],
  },
];

/** Non-album page on the home grid. Content lives in support-data.js (static; regenerate manually). */
window.PORTFOLIO_SUPPORT = {
  id: "Call for support",
  title: "Call for support",
  folder: "Call for support",
  thumbnail: "Call for support/call for support-logo.jpg",
  heroImage: "Call for support/mj.jpg",
  cardMeta: "Give Back",
};

window.PORTFOLIO_TRIBUTE = {
  id: "Tribute",
  title: "Tribute to",
  folder: "Tribute",
  thumbnail: "Tribute/tribute-logo.jpg",
  heroImage: "Tribute/mj.jpg",
  cardMeta: "my Masters",
};
